#!/usr/bin/env python3
"""Write the time-varying, sink-only ball-valve resistance fvOption."""

from __future__ import annotations

import argparse
from pathlib import Path


# Positive SuSp is assembled on the momentum diagonal and therefore damps U.
BETA_CLOSED = 1.0e10  # kg/(m3 s); acceptance is set by the leakage gate


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=Path("constant/fvOptions"))
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--opening-time", type=float)
    mode.add_argument("--closed", action="store_true")
    return parser.parse_args()


def ramp(opening_time: float | None, closed: bool) -> list[tuple[float, float]]:
    if closed:
        return [(0.0, BETA_CLOSED), (100.0, BETA_CLOSED)]
    if opening_time is None or opening_time <= 0:
        raise ValueError("opening-time must be positive")
    points: list[tuple[float, float]] = []
    for fraction in (0.0, 0.25, 0.50, 0.75, 1.0):
        beta = BETA_CLOSED * (1.0 - fraction) ** 4
        points.append((fraction * opening_time, beta))
    points.append((100.0, 0.0))
    return points


def main() -> None:
    args = parse_args()
    points = ramp(args.opening_time, args.closed)
    table = "\n".join(f"                ({time:.9g} {value:.9g})" for time, value in points)
    mode_note = "closed" if args.closed else f"opening over {args.opening_time:g} s"
    text = f"""/* Generated by configure_valve.py: {mode_note}.
   This option only removes momentum; it injects no pressure or velocity. */
FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      fvOptions;
}}

valveResistance
{{
    type            vectorSemiImplicitSource;
    active          yes;
    selectionMode   cellZone;
    cellZone        valveZone;
    volumeMode      specific;

    sources
    {{
        U
        {{
            implicit table
            (
{table}
            );
        }}
    }}
}}
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f"wrote {args.output} ({mode_note})")


if __name__ == "__main__":
    main()
