#!/usr/bin/env python3
"""Write the time-varying porous-baffle model for ball valve #4."""

from __future__ import annotations

import argparse
from pathlib import Path


D_CLOSED = 1.0e11  # 1/m2; acceptance is set by the closed-valve leakage gate
VALVE_LENGTH = 0.02  # m


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output", type=Path, default=Path("system/createBafflesDict")
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--opening-time", type=float)
    mode.add_argument("--closed", action="store_true")
    return parser.parse_args()


def ramp(opening_time: float | None, closed: bool) -> list[tuple[float, float]]:
    if closed:
        return [(0.0, D_CLOSED), (100.0, D_CLOSED)]
    if opening_time is None or opening_time <= 0:
        raise ValueError("opening-time must be positive")
    points: list[tuple[float, float]] = []
    for fraction in (0.0, 0.25, 0.50, 0.75, 1.0):
        darcy = D_CLOSED * (1.0 - fraction) ** 4
        points.append((fraction * opening_time, darcy))
    points.append((100.0, 0.0))
    return points


def main() -> None:
    args = parse_args()
    points = ramp(args.opening_time, args.closed)
    table = "\n".join(f"                ({time:.9g} {value:.9g})" for time, value in points)
    mode_note = "closed" if args.closed else f"opening over {args.opening_time:g} s"
    text = f"""/* Generated by configure_valve.py: {mode_note}.
   The cyclic porous baffle imposes only a passive flow-dependent pressure loss. */
FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      createBafflesDict;
}}

internalFacesOnly true;

baffles
{{
    ballValve4
    {{
        type        faceZone;
        zoneName    valveFaces;

        patches
        {{
            master
            {{
                name            valveUpstream;
                type            cyclic;
                neighbourPatch  valveDownstream;

                patchFields
                {{
                    U
                    {{
                        type cyclic;
                    }}
                    p
                    {{
                        type cyclic;
                    }}
                    p_rgh
                    {{
                        type            porousBafflePressure;
                        patchType       cyclic;
                        D table
                        (
{table}
                        );
                        I               0;
                        length          {VALVE_LENGTH:.9g};
                        uniformJump     true;
                        relax           0.1;
                        jump            uniform 0;
                        jump0           uniform 0;
                        value           uniform 101325;
                    }}
                    alpha.water
                    {{
                        type cyclic;
                    }}
                    T
                    {{
                        type cyclic;
                    }}
                }}
            }}
            slave
            {{
                name            valveDownstream;
                type            cyclic;
                neighbourPatch  valveUpstream;

                patchFields
                {{
                    ${{../../master/patchFields}}
                }}
            }}
        }}
    }}
}}
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f"wrote {args.output} ({mode_note})")


if __name__ == "__main__":
    main()
