#!/usr/bin/env python3
"""Write the time-varying effective-area model for ball valve #4."""

from __future__ import annotations

import argparse
from pathlib import Path


UPSTREAM_PRGH = 107786.6508
ATMOSPHERIC_PRESSURE = 101325.0
SAMPLE_FRACTIONS = (0.0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1.0)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output", type=Path, default=Path("system/createBafflesDict")
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--opening-time", type=float)
    mode.add_argument("--closed", action="store_true")
    return parser.parse_args()


def opening_table(
    opening_time: float | None, closed: bool
) -> list[tuple[float, float]]:
    if closed:
        return [(0.0, 0.0), (100.0, 0.0)]
    if opening_time is None or opening_time <= 0:
        raise ValueError("opening-time must be positive")

    # The paper reports only the total manual-opening duration.  A cubic
    # smoothstep gives a monotonic effective-area history with zero endpoint
    # slopes, without fitting any coefficient to the observed classification.
    points = []
    for fraction in SAMPLE_FRACTIONS:
        area_fraction = 3.0 * fraction**2 - 2.0 * fraction**3
        points.append((fraction * opening_time, area_fraction))
    points.append((100.0, 1.0))
    return points


def main() -> None:
    args = parse_args()
    points = opening_table(args.opening_time, args.closed)
    table = "\n".join(
        f"                    ({time:.9g} {value:.9g})"
        for time, value in points
    )
    mode_note = "closed" if args.closed else f"opening over {args.opening_time:g} s"
    text = f"""/* Generated by configure_valve.py: {mode_note}.
   The coupled area is the prescribed opening; the remainder is a no-slip wall. */
FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      createBafflesDict;
}}

internalFacesOnly true;

baffles
{{
    ballValve4
    {{
        type        faceZone;
        zoneName    valveFaces;

        patches
        {{
            master
            {{
                name            valveCoupleUpstream;
                type            cyclicACMI;
                neighbourPatch  valveCoupleDownstream;
                nonOverlapPatch valveWallUpstream;
                scale table
                (
{table}
                );

                patchFields
                {{
                    U
                    {{
                        type cyclicACMI;
                    }}
                    p
                    {{
                        type cyclicACMI;
                    }}
                    p_rgh
                    {{
                        type cyclicACMI;
                    }}
                    alpha.water
                    {{
                        type cyclicACMI;
                    }}
                    T
                    {{
                        type cyclicACMI;
                    }}
                }}
            }}
            slave
            {{
                name            valveCoupleDownstream;
                type            cyclicACMI;
                neighbourPatch  valveCoupleUpstream;
                nonOverlapPatch valveWallDownstream;

                patchFields
                {{
                    ${{../../master/patchFields}}
                }}
            }}
            master2
            {{
                name            valveWallUpstream;
                type            wall;

                patchFields
                {{
                    U
                    {{
                        type noSlip;
                    }}
                    p
                    {{
                        type calculated;
                        value uniform {UPSTREAM_PRGH:.9g};
                    }}
                    p_rgh
                    {{
                        type fixedFluxPressure;
                        value uniform {UPSTREAM_PRGH:.9g};
                    }}
                    alpha.water
                    {{
                        type constantAlphaContactAngle;
                        theta0 90;
                        limit gradient;
                        value uniform 1;
                    }}
                    T
                    {{
                        type zeroGradient;
                    }}
                }}
            }}
            slave2
            {{
                name            valveWallDownstream;
                type            wall;

                patchFields
                {{
                    U
                    {{
                        type noSlip;
                    }}
                    p
                    {{
                        type calculated;
                        value uniform {ATMOSPHERIC_PRESSURE:.9g};
                    }}
                    p_rgh
                    {{
                        type fixedFluxPressure;
                        value uniform {ATMOSPHERIC_PRESSURE:.9g};
                    }}
                    alpha.water
                    {{
                        type constantAlphaContactAngle;
                        theta0 90;
                        limit gradient;
                        value uniform 0;
                    }}
                    T
                    {{
                        type zeroGradient;
                    }}
                }}
            }}
        }}
    }}
}}
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f"wrote {args.output} ({mode_note})")


if __name__ == "__main__":
    main()
