#!/usr/bin/env python3
"""Generate small deterministic OpenFOAM runtime include files."""
from __future__ import annotations

import argparse
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--case-dir", type=Path, required=True)
    args = parser.parse_args()

    # Five samples on each plane resolve a bulk cross-sectional wet fraction
    # without mistaking one wall film for a filled mixture column.
    radial_points = ((0.0, 0.0), (0.015, 0.0), (-0.015, 0.0), (0.0, 0.015), (0.0, -0.015))
    z_levels = [0.46 + 0.02 * i for i in range(61)]  # 0.46 ... 1.66 m
    lines = [
        "            "
        + " ".join(
            f"({0.15 + dx:.5f} {dy:.5f} {z:.5f})" for dx, dy in radial_points
        )
        for z in z_levels
    ]
    target = args.case_dir / "system" / "riserProbeLocations"
    target.write_text(
        "// generated by ../prepare_runtime.py; level-major, five points/level\n"
        + "\n".join(lines)
        + "\n"
    )
    print(f"wrote {target} ({len(z_levels)} levels, {len(z_levels) * 5} probes)")

    tank_levels = [-0.36 + 0.01 * i for i in range(85)]  # -0.36 ... 0.48 m
    tank_target = args.case_dir / "system" / "tankProbeLocations"
    tank_target.write_text(
        "// generated by ../prepare_runtime.py; receiving-tank vertical stage line\n"
        + "            "
        + " ".join(f"(6.75000 0.25000 {z:.5f})" for z in tank_levels)
        + "\n"
    )
    print(f"wrote {tank_target} ({len(tank_levels)} probes)")


if __name__ == "__main__":
    main()
