#!/usr/bin/env python3
"""Materialize a reproducible OpenFOAM v2512 C9 source case.

Only parameters explicitly marked as paper values are fixed.  Pocket geometry
and tailgate opening remain named sensitivity inputs; see PAPER_AUDIT.md.
"""
from __future__ import annotations

import argparse
import json
import math
import os
from pathlib import Path

from make_geometry import build as build_geometry


HERE = Path(__file__).resolve().parent
CASE = HERE / "case"
PARAM_FILE = HERE / "case_parameters.json"


def foam_header(class_name: str, object_name: str) -> str:
    return f"""/* OpenFOAM v2512 source generated by prepare_case.py */
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {class_name};
    object      {object_name};
}}
"""


def write(relative: str, text: str, executable: bool = False) -> None:
    path = CASE / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")
    if executable:
        path.chmod(path.stat().st_mode | 0o111)


def field_file(name: str, class_name: str, dimensions: str, internal: str, boundary: str) -> str:
    return (
        foam_header(class_name, name)
        + f"""
dimensions      {dimensions};
internalField   {internal};
boundaryField
{{
{boundary}
}}
"""
    )


def perfect_fluid_eos_parameters(
    bulk_modulus: float,
    reference_density: float,
    reference_pressure: float,
    reference_temperature: float,
) -> tuple[float, float, float]:
    """Map physical K/rho data to OpenFOAM's rho=rho0+p/(R*T) EOS."""
    if min(
        bulk_modulus,
        reference_density,
        reference_pressure,
        reference_temperature,
    ) <= 0:
        raise ValueError("perfectFluid reference values must be positive")
    fluid_constant = bulk_modulus / (reference_density * reference_temperature)
    rho0 = reference_density - reference_pressure / (
        fluid_constant * reference_temperature
    )
    if rho0 <= 0:
        raise ValueError("perfectFluid rho0 must remain positive")
    wave_speed = math.sqrt(fluid_constant * reference_temperature)
    return fluid_constant, rho0, wave_speed


def cap_area(radius: float, height: float) -> float:
    height = max(0.0, min(2.0 * radius, height))
    return radius**2 * math.acos((radius - height) / radius) - (radius - height) * math.sqrt(
        max(0.0, 2.0 * radius * height - height**2)
    )


def analytic_pocket_volume(profile: dict, radius: float = 0.1) -> float:
    tail = profile["tail_x_m"]
    nose = profile["body_nose_x_m"]
    interface = profile["body_interface_z_m"]
    n = 10000
    dx = (nose - tail) / n
    body = 0.0
    for i in range(n):
        x = tail + (i + 0.5) * dx
        crown = 0.38 - 0.01 * x
        body += cap_area(radius, crown - interface) * dx
    return body + cap_area(radius, profile["thin_layer_m"]) * (0.0 - nose)


def generate_set_fields(paper: dict, model: dict, pocket: dict) -> str:
    q0 = paper["initial_flow_m3_s"]
    au = math.pi * paper["upstream_diameter_m"] ** 2 / 4.0
    ad = math.pi * paper["downstream_diameter_m"] ** 2 / 4.0
    uu = q0 / au
    ud = q0 / ad
    hgl = paper["chamber_height_m"] + paper["initial_riser_column_m"]
    rho = model["water_density_kg_m3"]
    g = 9.81
    patm = paper["atmospheric_pressure_Pa"]
    p_water_rgh = patm + rho * g * hgl
    p_pocket = patm + rho * g * (hgl - pocket["body_interface_z_m"])
    free_z = hgl

    regions = [
        f"""    boxToCell
    {{
        box (-5.81 -0.12 0.12) (0.01 0.12 0.46);
        fieldValues
        (
            volVectorFieldValue U ({uu:.10g} 0 {-paper['upstream_slope'] * uu:.10g})
        );
    }}""",
        f"""    boxToCell
    {{
        box (0.29 -0.16 -0.01) (6.26 0.16 0.30);
        fieldValues
        (
            volVectorFieldValue U ({ud:.10g} 0 0)
        );
    }}""",
        f"""    boxToCell
    {{
        box (-1 -1 {free_z:.8g}) (1 1 2.80);
        fieldValues
        (
            volScalarFieldValue alpha.water 0
            volScalarFieldValue p {patm:.10g}
            volScalarFieldValue p_rgh {patm:.10g}
            volVectorFieldValue U (0 0 0)
        );
    }}""",
        f"""    boxToCell
    {{
        box ({pocket['tail_x_m']:.8g} -0.12 {pocket['body_interface_z_m']:.8g})
            ({pocket['body_nose_x_m']:.8g} 0.12 0.46);
        fieldValues
        (
            volScalarFieldValue alpha.water 0
            volScalarFieldValue pocketBodyTracer 1
            volScalarFieldValue p {p_pocket:.10g}
            volScalarFieldValue p_rgh {p_pocket:.10g}
            volVectorFieldValue U (0 0 0)
        );
    }}""",
    ]

    # Resolve the thin crown layer with short boxes following the 1:100 pipe.
    nose = pocket["body_nose_x_m"]
    n_layer = max(8, int(math.ceil(-nose / 0.10)))
    for i in range(n_layer):
        x0 = nose + (0.0 - nose) * i / n_layer
        x1 = nose + (0.0 - nose) * (i + 1) / n_layer
        xm = 0.5 * (x0 + x1)
        crown = paper["invert_drop_m"] + paper["upstream_diameter_m"] - paper["upstream_slope"] * xm
        bottom = crown - pocket["thin_layer_m"]
        regions.append(
            f"""    boxToCell
    {{
        box ({x0:.8g} -0.12 {bottom:.8g}) ({x1:.8g} 0.12 0.46);
        fieldValues
        (
            volScalarFieldValue alpha.water 0
            volScalarFieldValue p {p_pocket:.10g}
            volScalarFieldValue p_rgh {p_pocket:.10g}
            volVectorFieldValue U (0 0 0)
        );
    }}"""
        )

    return (
        foam_header("dictionary", "setFieldsDict")
        + f"""
// HGL={hgl:.5f} m comes from chamber top + reported hr0.
// Pocket dimensions are the selected uncertainty profile, not paper values.
defaultFieldValues
(
    volScalarFieldValue alpha.water 1
    volScalarFieldValue pocketBodyTracer 0
    volScalarFieldValue p {p_water_rgh:.10g}
    volScalarFieldValue p_rgh {p_water_rgh:.10g}
    volScalarFieldValue T {paper['temperature_K']:.8g}
    volVectorFieldValue U (0 0 0)
);
regions
(
{os.linesep.join(regions)}
);
"""
    )


def generate_initial_field_correction(
    paper: dict, model: dict, pocket: dict
) -> str:
    """Return hydrostatic pressure and divergence-free gate-start corrections."""
    q0 = paper["initial_flow_m3_s"]
    upstream_radius = paper["upstream_diameter_m"] / 2.0
    chamber_start = 0.0
    chamber_end = paper["chamber_length_m"]
    upstream_axis_z = paper["invert_drop_m"] + upstream_radius
    downstream_radius = paper["downstream_diameter_m"] / 2.0
    downstream_axis_z = downstream_radius
    gate_radius = math.sqrt(model["tailgate_geometric_area_m2"] / math.pi)
    x_gate = paper["chamber_length_m"] + paper["downstream_length_m"]
    x_transition = x_gate - paper["downstream_diameter_m"]
    z_axis = downstream_radius
    upstream_p_rgh = (
        paper["atmospheric_pressure_Pa"]
        + model["water_density_kg_m3"]
        * 9.81
        * (paper["chamber_height_m"] + paper["initial_riser_column_m"])
    )
    tailwater_p_rgh = (
        paper["atmospheric_pressure_Pa"]
        + model["water_density_kg_m3"] * 9.81 * model["tailwater_level_m"]
    )
    rho_air = (
        paper["atmospheric_pressure_Pa"]
        + model["water_density_kg_m3"]
        * 9.81
        * (
            paper["chamber_height_m"]
            + paper["initial_riser_column_m"]
            - pocket["body_interface_z_m"]
        )
    ) / (
        (8314.46261815324 / model["air_molecular_weight_kg_kmol"])
        * paper["temperature_K"]
    )
    return (
        foam_header("dictionary", "setExprFieldsDict")
        + f"""
// setFields supplies phase topology and piecewise hydraulic estimates.
// These expressions then ramp p_rgh to the tailwater boundary, enforce
// p = p_rgh + rho*g.z, and replace discontinuous chamber/gate velocity boxes
// with smooth axisymmetric constant-Q streamtubes.  The correction changes no
// pocket coordinate, volume prior, gate area, or paper-time forcing.
readFields (alpha.water p_rgh U);

expressions
(
    gatePressureRamp
    {{
        field p_rgh;
        dimensions [1 -1 -2 0 0 0 0];
        variables
        (
            "x0 = {x_transition:.12g}"
            "x1 = {x_gate:.12g}"
            "xi = min(max((pos().x() - x0)/(x1 - x0), 0), 1)"
            "smooth = 3*sqr(xi) - 2*xi*sqr(xi)"
        );
        fieldMask "pos().x() >= x0";
        expression
        #{{
            {upstream_p_rgh:.12g}
          + ({tailwater_p_rgh:.12g} - {upstream_p_rgh:.12g})*smooth
        #}};
    }}

    hydrostaticPressure
    {{
        field p;
        dimensions [1 -1 -2 0 0 0 0];
        expression
        #{{
            p_rgh
          + (alpha.water*{model['water_density_kg_m3']:.12g}
          + (1 - alpha.water)*{rho_air:.12g})
           *((vector(0, 0, -9.81)) & pos())
        #}};
    }}

    stopChamberBackground
    {{
        field U;
        dimensions [0 1 -1 0 0 0 0];
        fieldMask
        #{{
            (pos().x() >= {chamber_start:.12g})
         && (pos().x() <= {chamber_end:.12g})
        #}};
        expression "vector(0, 0, 0)";
    }}

    chamberStreamtube
    {{
        field U;
        dimensions [0 1 -1 0 0 0 0];
        variables
        (
            "x0 = {chamber_start:.12g}"
            "x1 = {chamber_end:.12g}"
            "length = x1 - x0"
            "xi = min(max((pos().x() - x0)/length, 0), 1)"
            "smooth = 3*sqr(xi) - 2*xi*sqr(xi)"
            "radius0 = {upstream_radius:.12g}"
            "radius1 = {downstream_radius:.12g}"
            "radius = radius0 + (radius1 - radius0)*smooth"
            "drdx = (radius1 - radius0)*6*xi*(1 - xi)/length"
            "z0 = {upstream_axis_z:.12g}"
            "z1 = {downstream_axis_z:.12g}"
            "zaxis = z0 + (z1 - z0)*smooth"
            "dzdx = (z1 - z0)*6*xi*(1 - xi)/length"
            "speed = {q0:.12g}/(3.141592653589793*sqr(radius))"
            "radial = sqrt(sqr(pos().y()) + sqr(pos().z() - zaxis))"
        );
        fieldMask
        #{{
            (pos().x() >= x0)
         && (pos().x() <= x1)
         && (radial <= radius)
        #}};
        expression
        #{{
            vector
            (
                speed,
                pos().y()*speed*drdx/radius,
                speed*dzdx + (pos().z() - zaxis)*speed*drdx/radius
            )
        #}};
    }}

    stopGateAnnulus
    {{
        field U;
        dimensions [0 1 -1 0 0 0 0];
        fieldMask "pos().x() >= {x_transition:.12g}";
        expression "vector(0, 0, 0)";
    }}

    convergingGateCore
    {{
        field U;
        dimensions [0 1 -1 0 0 0 0];
        variables
        (
            "x0 = {x_transition:.12g}"
            "x1 = {x_gate:.12g}"
            "length = x1 - x0"
            "xi = min(max((pos().x() - x0)/length, 0), 1)"
            "smooth = 3*sqr(xi) - 2*xi*sqr(xi)"
            "radius0 = {downstream_radius:.12g}"
            "radius1 = {gate_radius:.12g}"
            "radius = radius0 + (radius1 - radius0)*smooth"
            "drdx = (radius1 - radius0)*6*xi*(1 - xi)/length"
            "speed = {q0:.12g}/(3.141592653589793*sqr(radius))"
            "radial = sqrt(sqr(pos().y()) + sqr(pos().z() - {z_axis:.12g}))"
        );
        fieldMask
        #{{
            (pos().x() >= x0)
         && (pos().x() <= x1 + 0.01)
         && (radial <= radius)
        #}};
        expression
        #{{
            vector
            (
                speed,
                pos().y()*speed*drdx/radius,
                (pos().z() - {z_axis:.12g})*speed*drdx/radius
            )
        #}};
    }}
);
"""
    )


def make_control_dict(
    application: str,
    end_time: float,
    write_interval: float,
    max_co: float,
    max_alpha_co: float,
    max_dt: float,
    paper: dict,
    model: dict,
    pocket: dict,
) -> str:
    ramp = model["ramp_start_solver_s"]
    q0 = paper["initial_flow_m3_s"]
    q1 = paper["final_flow_m3_s"]
    ramp_end = ramp + paper["flow_ramp_s"]
    top = paper["chamber_height_m"] + paper["riser_length_m"] + model["plume_height_above_rim_m"]
    z_values = [0.46 + i * (top - 0.46) / 110.0 for i in range(111)]
    riser_points = "\n".join(f"            (0.15 0.0 {z:.6f})" for z in z_values)
    crown_points = []
    deep_crown_points = []
    main_body_probe_depth = pocket["thin_layer_m"] + 0.004
    for i in range(60):
        x = -5.75 + i * 5.70 / 59.0
        crown = 0.38 - 0.01 * x
        crown_points.append(f"            ({x:.6f} 0 {crown - 0.004:.6f})")
        deep_crown_points.append(
            f"            ({x:.6f} 0 {crown - main_body_probe_depth:.6f})"
        )

    return (
        foam_header("dictionary", "controlDict")
        + f"""
application     {application};
startFrom       latestTime;
startTime       0;
stopAt          endTime;
endTime         {end_time:.10g};
deltaT          1e-6;
writeControl    adjustableRunTime;
writeInterval   {write_interval:.10g};
purgeWrite      4;
writeFormat     binary;
writePrecision  8;
writeCompression off;
timeFormat      general;
timePrecision   10;
runTimeModifiable yes;

adjustTimeStep  yes;
maxCo           {max_co:.8g};
maxAlphaCo      {max_alpha_co:.8g};
maxDeltaT       {max_dt:.8g};

functions
{{
    tracerAirFraction
    {{
        // Residual air fraction keeps the compressible scalar matrix
        // non-singular in pure-water cells without transporting tracer there.
        type            exprField;
        libs            (fieldFunctionObjects);
        field           alphaAirForTracer;
        expression      "alpha.air + 1e-8";
        store           true;
        autowrite       false;
        enabled         true;
        log             false;
        executeControl  timeStep;
        executeInterval 1;
        writeControl    none;
    }}

    tracerAirMassDensity
    {{
        type            multiply;
        libs            (fieldFunctionObjects);
        fields          (alphaAirForTracer thermo:rho.air);
        result          alphaRhoAirForTracer;
        enabled         true;
        log             false;
        executeControl  timeStep;
        executeInterval 1;
        writeControl    none;
    }}

    tracerWaterDensityFaces
    {{
        type            surfaceInterpolate;
        libs            (fieldFunctionObjects);
        fields          ((thermo:rho.water waterDensityFaceForTracer));
        enabled         true;
        log             false;
        executeControl  timeStep;
        executeInterval 1;
        writeControl    none;
    }}

    tracerWaterMassFlux
    {{
        // Field multiplication preserves the kg/s dimensions required for
        // subtraction from rhoPhi.  exprField otherwise defaults a newly
        // created surface field to dimensionless.
        type            multiply;
        libs            (fieldFunctionObjects);
        fields          (waterDensityFaceForTracer alphaPhi0.water);
        result          waterMassFluxForTracer;
        enabled         true;
        log             false;
        executeControl  timeStep;
        executeInterval 1;
        writeControl    none;
    }}

    tracerAirMassFlux
    {{
        // compressibleInterFoam mixture mass flux minus its conservative
        // water-phase contribution gives the air-phase mass flux.
        type            subtract;
        libs            (fieldFunctionObjects);
        fields          (rhoPhi waterMassFluxForTracer);
        result          airMassFluxForTracer;
        enabled         true;
        log             false;
        executeControl  timeStep;
        executeInterval 1;
        writeControl    none;
    }}

    pocketBodyTracerTransport
    {{
        type            scalarTransport;
        libs            (solverFunctionObjects);
        field           pocketBodyTracer;
        phi             airMassFluxForTracer;
        rho             alphaRhoAirForTracer;
        schemesField    pocketBodyTracer;
        bounded01       true;
        D               0;
        tolerance       1e-8;
        nCorr           0;
        resetOnStartUp  false;
        enabled         true;
        log             false;
        executeControl  timeStep;
        executeInterval 1;
        writeControl    writeTime;
        writeInterval   1;
    }}

    probesPT
    {{
        type            probes;
        libs            (sampling);
        fields          (p p_rgh alpha.water U pocketBodyTracer);
        probeLocations
        (
            (0.15 -0.025 1.25)     // PT1: riser wall, +0.80 m
            (0.15 -0.08  0.44)     // PT2: chamber top
            (0.15 -0.14  0.02)     // PT3: chamber front wall, +0.02 m
            (-0.30 0 {0.38 - 0.01 * (-0.30) - 0.004:.6f}) // PT4 crown
        );
        writeControl    adjustableRunTime;
        writeInterval   0.002;
    }}

    riserCentreline
    {{
        type            probes;
        libs            (sampling);
        fields          (alpha.water U p);
        probeLocations
        (
{riser_points}
        );
        writeControl    adjustableRunTime;
        writeInterval   0.005;
    }}

    upstreamCrown
    {{
        type            probes;
        libs            (sampling);
        fields          (alpha.water p pocketBodyTracer);
        probeLocations
        (
{os.linesep.join(crown_points)}
        );
        writeControl    adjustableRunTime;
        writeInterval   0.01;
    }}

    upstreamCrownDeep
    {{
        // Four millimetres below the selected thin-layer prior.  Gas at this
        // depth identifies the thick main pocket instead of the initially
        // connected crown layer.
        type            probes;
        libs            (sampling);
        fields          (alpha.water p pocketBodyTracer);
        probeLocations
        (
{os.linesep.join(deep_crown_points)}
        );
        writeControl    adjustableRunTime;
        writeInterval   0.01;
    }}

    totalMass
    {{
        type            volFieldValue;
        libs            (fieldFunctionObjects);
        operation       volIntegrate;
        fields          (rho);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    waterVolume
    {{
        type            volFieldValue;
        libs            (fieldFunctionObjects);
        operation       volIntegrate;
        fields          (alpha.water);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    waterMass
    {{
        type            volFieldValue;
        libs            (fieldFunctionObjects);
        operation       weightedVolIntegrate;
        weightField     alpha.water;
        fields          (thermo:rho.water);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    gasMass
    {{
        type            volFieldValue;
        libs            (fieldFunctionObjects);
        operation       weightedVolIntegrate;
        weightField     alpha.air;
        fields          (thermo:rho.air);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    upstreamWaterVolume
    {{
        type            volFieldValue;
        libs            (fieldFunctionObjects);
        regionType      cellZone;
        name            upstreamPipe;
        operation       volIntegrate;
        fields          (alpha.water);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    upstreamMass
    {{
        type            volFieldValue;
        libs            (fieldFunctionObjects);
        regionType      cellZone;
        name            upstreamPipe;
        operation       volIntegrate;
        fields          (rho);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    upstreamWaterMass
    {{
        type            volFieldValue;
        libs            (fieldFunctionObjects);
        regionType      cellZone;
        name            upstreamPipe;
        operation       weightedVolIntegrate;
        weightField     alpha.water;
        fields          (thermo:rho.water);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    upstreamGasMass
    {{
        type            volFieldValue;
        libs            (fieldFunctionObjects);
        regionType      cellZone;
        name            upstreamPipe;
        operation       weightedVolIntegrate;
        weightField     alpha.air;
        fields          (thermo:rho.air);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    chamberWaterVolume
    {{
        type            volFieldValue;
        libs            (fieldFunctionObjects);
        regionType      cellZone;
        name            chamber;
        operation       volIntegrate;
        fields          (alpha.water);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    totalPocketBodyTracerMass
    {{
        type            volFieldValue;
        libs            (fieldFunctionObjects);
        operation       weightedVolIntegrate;
        weightField     alphaRhoAirForTracer;
        fields          (pocketBodyTracer);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    upstreamPocketBodyTracerMass
    {{
        type            volFieldValue;
        libs            (fieldFunctionObjects);
        regionType      cellZone;
        name            upstreamPipe;
        operation       weightedVolIntegrate;
        weightField     alphaRhoAirForTracer;
        fields          (pocketBodyTracer);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    chamberPocketBodyTracerMass
    {{
        type            volFieldValue;
        libs            (fieldFunctionObjects);
        regionType      cellZone;
        name            chamber;
        operation       weightedVolIntegrate;
        weightField     alphaRhoAirForTracer;
        fields          (pocketBodyTracer);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    riserPocketBodyTracerMass
    {{
        type            volFieldValue;
        libs            (fieldFunctionObjects);
        regionType      cellZone;
        name            riser;
        operation       weightedVolIntegrate;
        weightField     alphaRhoAirForTracer;
        fields          (pocketBodyTracer);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    inletFlux
    {{
        type            surfaceFieldValue;
        libs            (fieldFunctionObjects);
        regionType      patch;
        name            inlet;
        operation       sum;
        fields          (phi rhoPhi);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    inletWaterMassFlux
    {{
        type            surfaceFieldValue;
        libs            (fieldFunctionObjects);
        regionType      patch;
        name            inlet;
        operation       weightedSum;
        weightField     thermo:rho.water;
        fields          (alphaPhi0.water);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    gateFlux
    {{
        type            surfaceFieldValue;
        libs            (fieldFunctionObjects);
        regionType      patch;
        name            gateOutlet;
        operation       sum;
        fields          (phi rhoPhi);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    gateWaterMassFlux
    {{
        type            surfaceFieldValue;
        libs            (fieldFunctionObjects);
        regionType      patch;
        name            gateOutlet;
        operation       weightedSum;
        weightField     thermo:rho.water;
        fields          (alphaPhi0.water);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    atmosphereFlux
    {{
        type            surfaceFieldValue;
        libs            (fieldFunctionObjects);
        regionType      patch;
        name            atmosphere;
        operation       sum;
        fields          (phi rhoPhi);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    atmosphereWaterMassFlux
    {{
        type            surfaceFieldValue;
        libs            (fieldFunctionObjects);
        regionType      patch;
        name            atmosphere;
        operation       weightedSum;
        weightField     thermo:rho.water;
        fields          (alphaPhi0.water);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
        writeFields     false;
    }}

    extrema
    {{
        type            fieldMinMax;
        libs            (fieldFunctionObjects);
        mode            magnitude;
        fields          (p rho alpha.water U pocketBodyTracer);
        writeControl    adjustableRunTime;
        writeInterval   0.01;
    }}
}}

// Inlet flow-rate table is part of U.  Solver time {ramp:.3f} s is paper t=0:
// Q={q0:.6f} until then, ramp to {q1:.6f} by {ramp_end:.3f} s.
"""
    )


def generate(args: argparse.Namespace) -> dict:
    with PARAM_FILE.open(encoding="utf-8") as stream:
        raw = json.load(stream)
    paper = raw["paper"]
    model = raw["model"].copy()
    mesh = raw["mesh_profiles"][args.mesh_profile]
    pocket = model["pocket_profiles"][args.pocket_profile].copy()
    thin_layer_cell_size = (
        args.thin_layer_cell_size
        if args.thin_layer_cell_size is not None
        else mesh["cartesian_thin_layer_cell_size_m"]
    )
    if thin_layer_cell_size <= 0:
        raise ValueError("cartesian thin-layer cell size must be positive")
    if args.air_cp is not None:
        model["air_Cp_J_kg_K"] = args.air_cp
    water_bulk_overridden = args.water_bulk_modulus is not None
    if water_bulk_overridden:
        model["water_bulk_modulus_Pa"] = args.water_bulk_modulus
    else:
        model["water_bulk_modulus_Pa"] = (
            model["water_density_kg_m3"]
            * paper["downstream_pressure_wave_speed_m_s"] ** 2
        )
    if model["water_bulk_modulus_Pa"] <= 0:
        raise ValueError("water bulk modulus must be positive")
    turbulence_model = args.turbulence_model or model["turbulence_model"]

    gate_area = args.gate_area if args.gate_area is not None else model["tailgate_geometric_area_m2"]
    model["tailgate_geometric_area_m2"] = gate_area
    contact_angle = args.contact_angle if args.contact_angle is not None else model["contact_angle_deg"]
    c_alpha = args.c_alpha if args.c_alpha is not None else model["interface_compression"]
    velocity_limit = args.velocity_limit
    application = (
        "compressibleInterIsoFoam"
        if args.interface_solver == "iso-advector"
        else "compressibleInterFoam"
    )
    if args.interface_solver == "iso-advector":
        alpha_settings = f"""nAlphaCorr 1;
        nAlphaSubCycles 1;
        cAlpha {c_alpha:.8g};
        reconstructionScheme isoAlpha;
        vof2IsoTol 1e-8;
        surfCellTol 1e-6;
        nAlphaBounds 3;
        snapTol 1e-12;
        clip true;"""
    else:
        alpha_settings = f"""nAlphaCorr 1;
        nAlphaSubCycles 2;
        cAlpha {c_alpha:.8g};
        MULESCorr no;
        nLimiterIter 5;
        solver smoothSolver;
        smoother symGaussSeidel;
        tolerance 1e-8;
        relTol 0;"""
    geometry_meta = build_geometry(gate_area)

    lu = paper["upstream_length_m"]
    lc = paper["chamber_length_m"]
    ld = paper["downstream_length_m"]
    dd = paper["downstream_diameter_m"]
    dr = paper["riser_diameter_m"]
    z_rim = paper["chamber_height_m"] + paper["riser_length_m"]
    z_top = geometry_meta["plume_top_z_m"]
    tail = pocket["tail_x_m"]
    nose = pocket["body_nose_x_m"]
    pocket_interface = pocket["body_interface_z_m"]
    thin_layer = pocket["thin_layer_m"]
    nx, ny, nz = mesh["background_cells"]

    write(
        "system/blockMeshDict",
        foam_header("dictionary", "blockMeshDict")
        + f"""
scale 1;
vertices
(
    (-5.90 -0.32 -0.05) (6.35 -0.32 -0.05)
    ( 6.35  0.32 -0.05) (-5.90  0.32 -0.05)
    (-5.90 -0.32  2.72) (6.35 -0.32  2.72)
    ( 6.35  0.32  2.72) (-5.90  0.32  2.72)
);
blocks
(
    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)
);
edges ();
boundary
(
    allBoundary
    {{
        type patch;
        faces ((3 7 6 2) (0 4 7 3) (2 6 5 1) (1 5 4 0) (0 3 2 1) (4 5 6 7));
    }}
);
"""
    )

    surfaces = ("walls", "riserWall", "inlet", "gateWall", "gateOutlet", "atmosphere")
    feature_entries = "\n".join(
        f"""    {name}.stl
    {{
        extractionMethod extractFromSurface;
        extractFromSurfaceCoeffs {{ includedAngle 150; }}
        writeObj no;
    }}"""
        for name in surfaces
    )
    write(
        "system/surfaceFeatureExtractDict",
        foam_header("dictionary", "surfaceFeatureExtractDict") + feature_entries,
    )
    thin_refinement_entries = []
    n_thin_refinement = max(8, int(math.ceil(-nose / 0.10)))
    pipe_radius = paper["upstream_diameter_m"] / 2.0
    thin_half_width = math.sqrt(max(0.0, 2.0 * pipe_radius * thin_layer - thin_layer**2))
    thin_refinement_width = min(2.0 * pipe_radius, 2.0 * thin_half_width + 0.012)
    for i in range(n_thin_refinement):
        x0 = nose + (0.0 - nose) * i / n_thin_refinement
        x1 = nose + (0.0 - nose) * (i + 1) / n_thin_refinement
        xm = 0.5 * (x0 + x1)
        crown = paper["invert_drop_m"] + paper["upstream_diameter_m"] - paper[
            "upstream_slope"
        ] * xm
        thin_refinement_entries.append(
            f"""    thinLayer{i:02d}
    {{
        type box;
        cellSize {thin_layer_cell_size:.8g};
        centre ({xm:.8g} 0 {crown - 0.5 * thin_layer:.8g});
        lengthX {x1 - x0 + 0.005:.8g};
        lengthY {thin_refinement_width:.8g};
        lengthZ {thin_layer + 0.004:.8g};
    }}"""
        )
    write(
        "system/meshDict",
        foam_header("dictionary", "meshDict")
        + f"""
// cfMesh Cartesian path.  Physical cell sizes retain the same local-resolution
// intent as the snappyHexMesh levels while avoiding concave transition cells.
surfaceFile "constant/triSurface/c9Rig.stl";
maxCellSize {mesh['cartesian_max_cell_size_m']:.8g};
boundaryCellSize {mesh['cartesian_boundary_cell_size_m']:.8g};

objectRefinements
{{
    chamber
    {{
        type box;
        cellSize {mesh['cartesian_chamber_cell_size_m']:.8g};
        centre (0.15 0 0.265);
        lengthX 0.90;
        lengthY 0.40;
        lengthZ 0.57;
    }}
    riser
    {{
        type cone;
        cellSize {mesh['cartesian_riser_cell_size_m']:.8g};
        p0 (0.15 0 0.43);
        radius0 0.04;
        p1 (0.15 0 {z_rim + 0.03:.8g});
        radius1 0.04;
    }}
    pocket
    {{
        type box;
        cellSize {mesh['cartesian_pocket_cell_size_m']:.8g};
        centre ({0.5 * (tail - 0.10 + 0.05):.8g} 0 0.39);
        lengthX {0.05 - (tail - 0.10):.8g};
        lengthY 0.205;
        lengthZ 0.14;
    }}
    pocketTail
    {{
        type box;
        cellSize {mesh['cartesian_interface_cell_size_m']:.8g};
        centre ({tail:.8g} 0 0.395);
        lengthX 0.36;
        lengthY 0.18;
        lengthZ 0.08;
    }}
    pocketNose
    {{
        type box;
        cellSize {mesh['cartesian_interface_cell_size_m']:.8g};
        centre ({nose:.8g} 0 0.395);
        lengthX 0.50;
        lengthY 0.18;
        lengthZ 0.08;
    }}
    pocketInterface
    {{
        type box;
        cellSize {mesh['cartesian_interface_cell_size_m']:.8g};
        centre ({0.5 * (tail + nose):.8g} 0 {pocket_interface:.8g});
        lengthX {nose - tail + 0.16:.8g};
        lengthY 0.18;
        lengthZ 0.012;
    }}
{os.linesep.join(thin_refinement_entries)}
    gate
    {{
        type cone;
        cellSize {mesh['cartesian_gate_cell_size_m']:.8g};
        p0 ({lc + ld - 0.25:.8g} 0 {dd / 2:.8g});
        radius0 0.15;
        p1 ({lc + ld + 0.02:.8g} 0 {dd / 2:.8g});
        radius1 0.15;
    }}
}}

boundaryLayers
{{
    nLayers 0;
}}

renameBoundary
{{
    newPatchNames
    {{
        walls       {{ newName walls;       type wall; }}
        riserWall   {{ newName riserWall;   type wall; }}
        inlet       {{ newName inlet;       type patch; }}
        gateWall    {{ newName gateWall;    type wall; }}
        gateOutlet  {{ newName gateOutlet;  type patch; }}
        atmosphere  {{ newName atmosphere;  type patch; }}
    }}
}}
""",
    )

    geometry_entries = "\n".join(
        f"    {name}.stl {{ type triSurfaceMesh; name {name}; }}" for name in surfaces
    )
    feature_list = "\n".join(
        f'        {{ file "{name}.eMesh"; level {mesh["surface_level"]}; }}' for name in surfaces
    )
    surface_refine = "\n".join(
        f"""        {name}
        {{
            level ({mesh['riser_level'] if name == 'riserWall' else mesh['gate_level'] if name in ('gateWall', 'gateOutlet') else mesh['surface_level']}
                   {mesh['riser_level'] if name == 'riserWall' else mesh['gate_level'] if name in ('gateWall', 'gateOutlet') else mesh['surface_level']});
            patchInfo {{ type {'wall' if name in ('walls', 'riserWall', 'gateWall') else 'patch'}; }}
        }}"""
        for name in surfaces
    )
    write(
        "system/snappyHexMeshDict",
        foam_header("dictionary", "snappyHexMeshDict")
        + f"""
castellatedMesh true;
snap true;
addLayers false;

geometry
{{
{geometry_entries}
    chamberZone
    {{
        type searchableBox;
        min (-0.30 -0.20 -0.02);
        max ( 0.60  0.20  0.55);
    }}
    riserZone
    {{
        type searchableCylinder;
        point1 (0.15 0 0.43);
        point2 (0.15 0 {z_rim + 0.03:.6f});
        radius 0.034;
    }}
    plumeCore
    {{
        type searchableCylinder;
        point1 (0.15 0 {z_rim:.6f});
        point2 (0.15 0 {z_top:.6f});
        radius 0.09;
    }}
    pocketZone
    {{
        type searchableBox;
        min ({tail - 0.10:.6f} -0.12 {pocket['body_interface_z_m'] - 0.02:.6f});
        max (0.05 0.12 0.46);
    }}
    pocketTail
    {{
        type searchableBox;
        min ({tail - 0.18:.6f} -0.12 0.32);
        max ({tail + 0.18:.6f} 0.12 0.47);
    }}
    pocketNose
    {{
        type searchableBox;
        min ({nose - 0.25:.6f} -0.12 0.32);
        max ({nose + 0.25:.6f} 0.12 0.47);
    }}
    pocketInterface
    {{
        type searchableBox;
        min ({tail - 0.08:.6f} -0.12 {pocket_interface - 0.015:.6f});
        max ({nose + 0.08:.6f} 0.12 {pocket_interface + 0.015:.6f});
    }}
    thinLayerZone
    {{
        // The reported crown layer is only 8 mm in the base prior.  The old
        // 10 mm cells represented it by one cell and generated a >12 m/s
        // gas jet at the pocket nose.  Resolve it with at least three cells.
        type searchableBox;
        min ({nose - 0.08:.6f} -0.12 {0.38 - thin_layer - 0.012:.6f});
        max (0.02 0.12 {0.38 - 0.01 * nose + 0.008:.6f});
    }}
    riserFreeSurface
    {{
        type searchableCylinder;
        point1 (0.15 0 0.68);
        point2 (0.15 0 0.82);
        radius 0.04;
    }}
    gateZone
    {{
        type searchableCylinder;
        point1 ({lc + ld - 0.25:.6f} 0 {dd / 2:.6f});
        point2 ({lc + ld + 0.02:.6f} 0 {dd / 2:.6f});
        radius 0.15;
    }}
}}

castellatedMeshControls
{{
    maxLocalCells 1500000;
    maxGlobalCells {mesh['max_global_cells']};
    minRefinementCells 10;
    maxLoadUnbalance 0.10;
    nCellsBetweenLevels 2;
    features
    (
{feature_list}
    );
    refinementSurfaces
    {{
{surface_refine}
    }}
    resolveFeatureAngle 30;
    refinementRegions
    {{
        chamberZone      {{ mode inside; levels ((1e15 {mesh['chamber_level']})); }}
        riserZone        {{ mode inside; levels ((1e15 {mesh['riser_level']})); }}
        plumeCore        {{ mode inside; levels ((1e15 1)); }}
        pocketZone       {{ mode inside; levels ((1e15 {mesh['pocket_level']})); }}
        pocketTail       {{ mode inside; levels ((1e15 {mesh['interface_level']})); }}
        pocketNose       {{ mode inside; levels ((1e15 {mesh['interface_level']})); }}
        pocketInterface  {{ mode inside; levels ((1e15 {mesh['interface_level']})); }}
        thinLayerZone    {{ mode inside; levels ((1e15 {mesh['thin_layer_level']})); }}
        riserFreeSurface {{ mode inside; levels ((1e15 {mesh['interface_level']})); }}
        gateZone         {{ mode inside; levels ((1e15 {mesh['gate_level']})); }}
    }}
    locationInMesh (0.15 0 0.20);
    allowFreeStandingZoneFaces true;
}}
snapControls
{{
    nSmoothPatch 5;
    nSmoothInternal 3;
    tolerance 2.0;
    nSolveIter 80;
    nRelaxIter 8;
    nFeatureSnapIter 15;
    nFaceSplitInterval 5;
    concaveAngle 30;
    implicitFeatureSnap false;
    explicitFeatureSnap true;
    multiRegionFeatureSnap false;
    strictRegionSnap true;
}}
addLayersControls
{{
    relativeSizes true;
    layers {{}}
    expansionRatio 1.2;
    finalLayerThickness 0.5;
    minThickness 0.25;
    nGrow 0;
    featureAngle 60;
    slipFeatureAngle 30;
    nRelaxIter 3;
    nSmoothSurfaceNormals 1;
    nSmoothNormals 3;
    nSmoothThickness 10;
    maxFaceThicknessRatio 0.5;
    maxThicknessToMedialRatio 0.3;
    minMedialAxisAngle 90;
    nBufferCellsNoExtrude 0;
    nLayerIter 50;
}}
meshQualityControls
{{
    maxNonOrtho 65;
    maxBoundarySkewness 20;
    maxInternalSkewness 4;
    maxConcave 80;
    minVol 1e-13;
    minTetQuality 1e-15;
    minArea -1;
    minTwist 0.02;
    minDeterminant 0.001;
    minFaceWeight 0.05;
    minVolRatio 0.01;
    minTriangleTwist -1;
    nSmoothScale 4;
    errorReduction 0.75;
}}
writeFlags (scalarLevels);
mergeTolerance 1e-6;
"""
    )

    write("system/setFieldsDict", generate_set_fields(paper, model, pocket))
    write(
        "system/setExprFieldsDict",
        generate_initial_field_correction(paper, model, pocket),
    )
    write(
        "system/topoSetDict",
        foam_header("dictionary", "topoSetDict")
        + """
actions
(
    {
        name upstreamPipeCells;
        type cellSet;
        action new;
        source boxToCell;
        box (-5.82 -0.12 0.14) (-0.001 0.12 0.46);
    }
    {
        name upstreamPipe;
        type cellZoneSet;
        action new;
        source setToCellZone;
        set upstreamPipeCells;
    }
    {
        name chamberCells;
        type cellSet;
        action new;
        source boxToCell;
        box (0 -0.16 -0.01) (0.30 0.16 0.449);
    }
    {
        name chamber;
        type cellZoneSet;
        action new;
        source setToCellZone;
        set chamberCells;
    }
    {
        name riserCells;
        type cellSet;
        action new;
        source cylinderToCell;
        p1 (0.15 0 0.451);
        p2 (0.15 0 1.68);
        radius 0.032;
    }
    {
        name riser;
        type cellZoneSet;
        action new;
        source setToCellZone;
        set riserCells;
    }
);
"""
    )

    def wall_alpha(name):
        return f"""    {name}
    {{
        type            constantAlphaContactAngle;
        theta0          {contact_angle:.8g};
        limit           gradient;
        value           uniform 1;
    }}"""

    write(
        "0.orig/alpha.water",
        field_file(
            "alpha.water",
            "volScalarField",
            "[0 0 0 0 0 0 0]",
            "uniform 1",
            f"""    inlet
    {{
        type fixedValue;
        value uniform 1;
    }}
    gateOutlet
    {{
        type inletOutlet;
        inletValue uniform 1;
        value uniform 1;
    }}
    atmosphere
    {{
        type inletOutlet;
        inletValue uniform 0;
        value uniform 0;
    }}
{wall_alpha('walls')}
{wall_alpha('riserWall')}
{wall_alpha('gateWall')}
    allBoundary {{ type zeroGradient; }}""",
        ),
    )

    write(
        "0.orig/pocketBodyTracer",
        field_file(
            "pocketBodyTracer",
            "volScalarField",
            "[0 0 0 0 0 0 0]",
            "uniform 0",
            """    inlet
    {
        type fixedValue;
        value uniform 0;
    }
    gateOutlet
    {
        type inletOutlet;
        inletValue uniform 0;
        value uniform 0;
    }
    atmosphere
    {
        type inletOutlet;
        inletValue uniform 0;
        value uniform 0;
    }
    walls { type zeroGradient; }
    riserWall { type zeroGradient; }
    gateWall { type zeroGradient; }
    allBoundary { type zeroGradient; }""",
        ),
    )

    ramp = model["ramp_start_solver_s"]
    ramp_end = ramp + paper["flow_ramp_s"]
    q0, q1 = paper["initial_flow_m3_s"], paper["final_flow_m3_s"]
    upstream_area = math.pi * paper["upstream_diameter_m"] ** 2 / 4.0
    upstream_speed = q0 / upstream_area
    turbulence_intensity = model["inlet_turbulence_intensity"]
    turbulence_length = model["inlet_turbulence_mixing_length_m"]
    k_initial = 1.5 * (turbulence_intensity * upstream_speed) ** 2
    omega_initial = math.sqrt(k_initial) / (0.09**0.25 * turbulence_length)

    def turbulence_inlet_outlet(value):
        return f"""    gateOutlet
    {{
        type inletOutlet;
        inletValue uniform {value:.10g};
        value uniform {value:.10g};
    }}
    atmosphere
    {{
        type inletOutlet;
        inletValue uniform {value:.10g};
        value uniform {value:.10g};
    }}"""

    def turbulence_walls(boundary_type, value):
        return "\n".join(
            f"""    {name}
    {{
        type {boundary_type};
        value uniform {value:.10g};
    }}"""
            for name in ("walls", "riserWall", "gateWall")
        )

    write(
        "0.orig/k",
        field_file(
            "k",
            "volScalarField",
            "[0 2 -2 0 0 0 0]",
            f"uniform {k_initial:.10g}",
            f"""    inlet
    {{
        type turbulentIntensityKineticEnergyInlet;
        intensity {turbulence_intensity:.10g};
        value uniform {k_initial:.10g};
    }}
{turbulence_inlet_outlet(k_initial)}
{turbulence_walls('kqRWallFunction', k_initial)}
    allBoundary {{ type zeroGradient; }}""",
        ),
    )
    write(
        "0.orig/omega",
        field_file(
            "omega",
            "volScalarField",
            "[0 0 -1 0 0 0 0]",
            f"uniform {omega_initial:.10g}",
            f"""    inlet
    {{
        type turbulentMixingLengthFrequencyInlet;
        mixingLength {turbulence_length:.10g};
        value uniform {omega_initial:.10g};
    }}
{turbulence_inlet_outlet(omega_initial)}
{turbulence_walls('omegaWallFunction', omega_initial)}
    allBoundary {{ type zeroGradient; }}""",
        ),
    )
    write(
        "0.orig/nut",
        field_file(
            "nut",
            "volScalarField",
            "[0 2 -1 0 0 0 0]",
            "uniform 0",
            f"""    inlet {{ type calculated; value uniform 0; }}
    gateOutlet {{ type calculated; value uniform 0; }}
    atmosphere {{ type calculated; value uniform 0; }}
{turbulence_walls('nutkWallFunction', 0)}
    allBoundary {{ type calculated; value uniform 0; }}""",
        ),
    )
    write(
        "0.orig/alphat",
        field_file(
            "alphat",
            "volScalarField",
            "[1 -1 -1 0 0 0 0]",
            "uniform 0",
            f"""    inlet {{ type calculated; value uniform 0; }}
    gateOutlet {{ type calculated; value uniform 0; }}
    atmosphere {{ type calculated; value uniform 0; }}
{turbulence_walls('compressible::alphatWallFunction', 0)}
    allBoundary {{ type calculated; value uniform 0; }}""",
        ),
    )

    write(
        "0.orig/U",
        field_file(
            "U",
            "volVectorField",
            "[0 1 -1 0 0 0 0]",
            "uniform (0 0 0)",
            f"""    inlet
    {{
        type flowRateInletVelocity;
        volumetricFlowRate table
        (
            (0 {q0:.10g})
            ({ramp:.10g} {q0:.10g})
            ({ramp_end:.10g} {q1:.10g})
            ({model['full_end_solver_s'] + 1:.10g} {q1:.10g})
        );
        value uniform (0 0 0);
    }}
    gateOutlet
    {{
        type pressureInletOutletVelocity;
        value uniform (0 0 0);
    }}
    atmosphere
    {{
        type pressureInletOutletVelocity;
        value uniform (0 0 0);
    }}
    walls {{ type noSlip; }}
    riserWall {{ type noSlip; }}
    gateWall {{ type noSlip; }}
    allBoundary {{ type zeroGradient; }}""",
        ),
    )

    p_init = paper["atmospheric_pressure_Pa"]
    tailwater_rgh = (
        paper["atmospheric_pressure_Pa"]
        + model["water_density_kg_m3"] * 9.81 * model["tailwater_level_m"]
    )
    pressure_calculated = """    inlet { type calculated; value uniform 101325; }
    gateOutlet { type calculated; value uniform 101325; }
    atmosphere { type calculated; value uniform 101325; }
    walls { type calculated; value uniform 101325; }
    riserWall { type calculated; value uniform 101325; }
    gateWall { type calculated; value uniform 101325; }
    allBoundary { type calculated; value uniform 101325; }"""
    write(
        "0.orig/p",
        field_file("p", "volScalarField", "[1 -1 -2 0 0 0 0]", f"uniform {p_init}", pressure_calculated),
    )
    write(
        "0.orig/p_rgh",
        field_file(
            "p_rgh",
            "volScalarField",
            "[1 -1 -2 0 0 0 0]",
            f"uniform {p_init}",
            f"""    inlet {{ type fixedFluxPressure; value uniform {p_init}; }}
    gateOutlet
    {{
        // Static hydrostatic tailwater closure: external HGL = Dd = 0.28 m.
        // A total-pressure BC at this high-speed orifice would subtract the
        // jet velocity head a second time.
        type fixedValue;
        value uniform {tailwater_rgh:.10g};
    }}
    atmosphere
    {{
        type prghPressure;
        p uniform {p_init};
        value uniform {p_init};
    }}
    walls {{ type fixedFluxPressure; value uniform {p_init}; }}
    riserWall {{ type fixedFluxPressure; value uniform {p_init}; }}
    gateWall {{ type fixedFluxPressure; value uniform {p_init}; }}
    allBoundary {{ type zeroGradient; }}""",
        ),
    )
    write(
        "0.orig/T",
        field_file(
            "T",
            "volScalarField",
            "[0 0 0 1 0 0 0]",
            f"uniform {paper['temperature_K']}",
            f"""    inlet {{ type fixedValue; value uniform {paper['temperature_K']}; }}
    gateOutlet
    {{
        type inletOutlet;
        inletValue uniform {paper['temperature_K']};
        value uniform {paper['temperature_K']};
    }}
    atmosphere
    {{
        type inletOutlet;
        inletValue uniform {paper['temperature_K']};
        value uniform {paper['temperature_K']};
    }}
    walls {{ type zeroGradient; }}
    riserWall {{ type zeroGradient; }}
    gateWall {{ type zeroGradient; }}
    allBoundary {{ type zeroGradient; }}""",
        ),
    )

    write(
        "constant/g",
        foam_header("uniformDimensionedVectorField", "g")
        + """
dimensions [0 1 -2 0 0 0 0];
value (0 0 -9.81);
""",
    )
    if turbulence_model == "kOmegaSST":
        turbulence_properties = """
simulationType RAS;

RAS
{
    RASModel        kOmegaSST;
    turbulence      on;
    printCoeffs     on;
}
"""
    else:
        turbulence_properties = "\nsimulationType laminar;\n"
    write(
        "constant/turbulenceProperties",
        foam_header("dictionary", "turbulenceProperties") + turbulence_properties,
    )
    write(
        "constant/thermophysicalProperties",
        foam_header("dictionary", "thermophysicalProperties")
        + f"""
phases (water air);
pMin 50000;
sigma
{{
    type constant;
    sigma {model['surface_tension_N_m']};
}}
""",
    )
    # OpenFOAM perfectFluid uses rho = rho0 + p/(R*T), so R must include
    # temperature.  Keep the requested reference density at atmospheric
    # pressure instead of treating rho0 as that reference density.
    water_r, water_rho0, water_wave_speed = perfect_fluid_eos_parameters(
        model["water_bulk_modulus_Pa"],
        model["water_density_kg_m3"],
        paper["atmospheric_pressure_Pa"],
        paper["temperature_K"],
    )
    write(
        "constant/thermophysicalProperties.water",
        foam_header("dictionary", "thermophysicalProperties")
        + f"""
thermoType
{{
    type heRhoThermo;
    mixture pureMixture;
    transport const;
    thermo hConst;
    equationOfState perfectFluid;
    specie specie;
    energy sensibleInternalEnergy;
}}
mixture
{{
    specie {{ molWeight 18.01528; }}
    equationOfState
    {{
        R {water_r:.10g};
        rho0 {water_rho0:.10g};
    }}
    thermodynamics {{ Cp 4182; Hf 0; }}
    transport {{ mu {model['water_dynamic_viscosity_Pa_s']}; Pr 7.0; }}
}}
""",
    )
    write(
        "constant/thermophysicalProperties.air",
        foam_header("dictionary", "thermophysicalProperties")
        + f"""
thermoType
{{
    type heRhoThermo;
    mixture pureMixture;
    transport const;
    thermo hConst;
    equationOfState perfectGas;
    specie specie;
    energy sensibleInternalEnergy;
}}
mixture
{{
    specie {{ molWeight {model['air_molecular_weight_kg_kmol']}; }}
    thermodynamics {{ Cp {model['air_Cp_J_kg_K']}; Hf 0; }}
    transport {{ mu {model['air_dynamic_viscosity_Pa_s']}; Pr 0.71; }}
}}
""",
    )

    write(
        "system/fvSchemes",
        foam_header("dictionary", "fvSchemes")
        + """
ddtSchemes { default Euler; }
gradSchemes { default Gauss linear; }
divSchemes
{
    div(phi,alpha) Gauss vanLeer;
    div(phirb,alpha) Gauss linear;
    div(phi,thermo:rho.water) Gauss upwind;
    div(phi,thermo:rho.air) Gauss upwind;
    div(rhoPhi,U) Gauss upwind;
    div(rhoPhi,T) Gauss upwind;
    div(rhoPhi,K) Gauss upwind;
    div(phi,p) Gauss upwind;
    div(rhoPhi,k) Gauss upwind;
    div(rhoPhi,omega) Gauss upwind;
    div(phi,pocketBodyTracer) Gauss upwind;
    div(((rho*nuEff)*dev2(T(grad(U))))) Gauss linear;
}
laplacianSchemes { default Gauss linear corrected; }
interpolationSchemes { default linear; }
snGradSchemes { default corrected; }
wallDist { method meshWave; }
"""
    )
    write(
        "system/fvSolution",
        foam_header("dictionary", "fvSolution")
        + f"""
solvers
{{
    "alpha.water.*"
    {{
        {alpha_settings}
    }}
    "pcorr.*"
    {{
        solver PCG;
        preconditioner
        {{
            preconditioner GAMG;
            tolerance 1e-5;
            relTol 0;
            smoother DICGaussSeidel;
        }}
        tolerance 1e-5;
        relTol 0;
        maxIter 100;
    }}
    ".*(rho|rhoFinal)" {{ solver diagonal; }}
    p_rgh
    {{
        solver GAMG;
        tolerance 1e-7;
        relTol 0.01;
        smoother DIC;
    }}
    p_rghFinal
    {{
        solver PCG;
        preconditioner
        {{
            preconditioner GAMG;
            tolerance 1e-7;
            relTol 0;
            nVcycles 2;
            smoother DICGaussSeidel;
            nPreSweeps 2;
        }}
        tolerance 1e-7;
        relTol 0;
        maxIter 50;
    }}
    "U.*"
    {{
        solver smoothSolver;
        smoother GaussSeidel;
        tolerance 1e-6;
        relTol 0.01;
        nSweeps 1;
    }}
    "(T|k|omega|pocketBodyTracer|B|nuTilda).*"
    {{
        solver smoothSolver;
        smoother symGaussSeidel;
        tolerance 1e-8;
        relTol 0.01;
        maxIter 100;
    }}
}}
PIMPLE
{{
    momentumPredictor yes;
    transonic no;
    nOuterCorrectors 1;
    nCorrectors 2;
    nNonOrthogonalCorrectors 1;
}}
"""
    )
    fv_options = foam_header("dictionary", "fvOptions")
    if velocity_limit > 0:
        fv_options += f"""
limitU
{{
    type limitVelocity;
    active yes;
    selectionMode all;
    max {velocity_limit:.8g};
}}
"""
    else:
        fv_options += "\n// Velocity clipping disabled for the control case.\n"
    write("system/fvOptions", fv_options)
    write(
        "system/decomposeParDict",
        foam_header("dictionary", "decomposeParDict")
        + f"""
numberOfSubdomains {args.np};
method scotch;
"""
    )

    stages = {
        "initialize": (model["ramp_start_solver_s"], 0.05),
        "smoke": (model["smoke_end_solver_s"], 0.10),
        "phase1": (model["phase1_end_solver_s"], 0.25),
        "full": (model["full_end_solver_s"], 0.50),
    }
    for stage, (end_time, write_interval) in stages.items():
        write(
            f"system/controlDict.{stage}",
            make_control_dict(
                application,
                end_time,
                write_interval,
                args.max_co,
                args.max_alpha_co,
                args.max_dt,
                paper,
                model,
                pocket,
            ),
        )
    write(
        "system/controlDict",
        make_control_dict(
            application,
            model["full_end_solver_s"],
            0.50,
            args.max_co,
            args.max_alpha_co,
            args.max_dt,
            paper,
            model,
            pocket,
        ),
    )

    bash_prefix = f"""#!/usr/bin/env bash
source /usr/lib/openfoam/openfoam2512/etc/bashrc
set -eo pipefail
cd "$(dirname "$0")"
NP="${{OPENFOAM_NP:-{args.np}}}"
SOURCE_SCHEMA_FILES=(
    generated_case.json
    0.orig/alpha.water 0.orig/pocketBodyTracer 0.orig/U 0.orig/p 0.orig/p_rgh
    0.orig/T 0.orig/k 0.orig/omega 0.orig/nut 0.orig/alphat
    constant/thermophysicalProperties
    constant/thermophysicalProperties.water
    constant/thermophysicalProperties.air
    constant/turbulenceProperties
    system/fvSchemes system/fvSolution system/fvOptions
    system/setFieldsDict system/setExprFieldsDict
    system/controlDict.initialize system/controlDict.smoke
    system/controlDict.phase1 system/controlDict.full
)
"""
    surface_name = (
        "c9Rig.stl" if args.mesh_generator == "cartesian" else "diagnosticCombined.stl"
    )
    if args.mesh_generator == "cartesian":
        mesh_command = """rm -rf constant/polyMesh processor*
export LD_LIBRARY_PATH="${FOAM_LIBBIN}:${FOAM_LIBBIN}/sys-openmpi:${LD_LIBRARY_PATH:-}"
cartesianMesh > log.cartesianMesh 2>&1
rm -rf 0
cp -r 0.orig 0
"""
    else:
        mesh_command = """rm -rf constant/polyMesh processor*
blockMesh > log.blockMesh 2>&1
surfaceFeatureExtract > log.surfaceFeatureExtract 2>&1
rm -rf 0
cp -r 0.orig 0
decomposePar -copyZero > log.decomposePar.mesh 2>&1
mpirun -np "$NP" snappyHexMesh -parallel -overwrite > log.snappyHexMesh 2>&1
reconstructParMesh -constant > log.reconstructParMesh 2>&1
rm -rf processor*
"""
    write(
        "Allrun.mesh",
        bash_prefix
        + f"""test "$NP" -eq {args.np} || {{
    echo "OPENFOAM_NP must match system/decomposeParDict ({args.np})" >&2
    exit 2
}}
surfaceCheck constant/triSurface/{surface_name} -checkSelfIntersection > log.surfaceCheck 2>&1
rg -q '^Surface is closed' log.surfaceCheck || {{
    echo "Combined C9 surface is not topologically closed; see log.surfaceCheck" >&2
    exit 2
}}
if rg -q '^Surface is self-intersecting' log.surfaceCheck; then
    echo "Combined C9 surface self-intersects; see log.surfaceCheck" >&2
    exit 2
fi
{mesh_command}
topoSet > log.topoSet 2>&1
checkMesh > log.checkMesh 2>&1
checkMesh -allGeometry -allTopology > log.checkMesh.all 2>&1
rg -q 'Mesh OK\\.' log.checkMesh || {{
    echo "C9 mesh failed the standard check; see log.checkMesh" >&2
    exit 3
}}
rg -q 'Mesh OK\\.' log.checkMesh.all || {{
    echo "C9 mesh failed the strict geometry/topology check; see log.checkMesh.all" >&2
    exit 4
}}
echo MESH_DONE
""",
        executable=True,
    )
    write(
        "Allrun.initialize",
        bash_prefix
        + f"""rm -rf processor* postProcessing
rm -f log.smoke log.phase1 log.full log.source.sha256
foamListTimes -rm >/dev/null 2>&1 || true
rm -rf 0
cp -r 0.orig 0
setFields > log.setFields 2>&1
setExprFields > log.setExprFields 2>&1
decomposePar -force > log.decomposePar 2>&1
sha256sum "${{SOURCE_SCHEMA_FILES[@]}}" > log.source.sha256
trap 'cp system/controlDict.full system/controlDict' EXIT
cp system/controlDict.initialize system/controlDict
mpirun -np "$NP" {application} -parallel > log.initialize 2>&1
echo INITIALIZATION_DONE
""",
        executable=True,
    )
    write(
        "Allrun.resume",
        bash_prefix
        + f"""STAGE="${{1:-full}}"
case "$STAGE" in
    smoke|phase1|full) ;;
    *) echo "usage: $0 [smoke|phase1|full]" >&2; exit 2 ;;
esac
test -d processor0 || {{ echo "No decomposed run; use ./Allrun.initialize" >&2; exit 2; }}
test -f log.source.sha256 || {{
    echo "No initialized-source schema; rerun ./Allrun.initialize" >&2
    exit 2
}}
sha256sum -c log.source.sha256 >/dev/null || {{
    echo "Case source changed after initialization; rerun ./Allrun.initialize" >&2
    exit 2
}}
for field in pocketBodyTracer k omega; do
    test -f "processor0/0/$field" || {{
        echo "Checkpoint schema lacks $field; rerun ./Allrun.initialize" >&2
        exit 2
    }}
done
pgrep -f '[c]ompressibleInterFoam.*-parallel|[c]ompressibleInterIsoFoam.*-parallel' >/dev/null && {{
    echo "A C9 solver is already running" >&2
    exit 2
}}
trap 'cp system/controlDict.full system/controlDict' EXIT
cp "system/controlDict.${{STAGE}}" system/controlDict
mpirun -np "$NP" {application} -parallel >> "log.${{STAGE}}" 2>&1
echo "${{STAGE^^}}_DONE"
""",
        executable=True,
    )
    write(
        "Allrun.smoke",
        """#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
./Allrun.initialize
./Allrun.resume smoke
""",
        executable=True,
    )
    write(
        "Allrun.phase1",
        """#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
test -d processor0 || ./Allrun.initialize
./Allrun.resume phase1
""",
        executable=True,
    )
    write(
        "Allrun.phase2",
        """#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
test -d processor0 || ./Allrun.phase1
./Allrun.resume full
""",
        executable=True,
    )
    write(
        "Allrun.solve",
        """#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
./Allrun.phase1
./Allrun.phase2
""",
        executable=True,
    )
    write(
        "Allrun.reconstruct",
        """#!/usr/bin/env bash
source /usr/lib/openfoam/openfoam2512/etc/bashrc
set -eo pipefail
cd "$(dirname "$0")"
reconstructPar -latestTime > log.reconstructPar 2>&1
""",
        executable=True,
    )
    write(
        "Allrun.postprocess",
        """#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
python3 ../postprocess_openfoam.py --case .
""",
        executable=True,
    )
    write(
        "Allclean",
        """#!/usr/bin/env bash
source /usr/lib/openfoam/openfoam2512/etc/bashrc
set -eo pipefail
cd "$(dirname "$0")"
rm -rf processor* postProcessing constant/polyMesh 0
foamListTimes -rm >/dev/null 2>&1 || true
rm -f log.*
""",
        executable=True,
    )

    analytic_volume = analytic_pocket_volume(pocket)
    hgl = paper["chamber_height_m"] + paper["initial_riser_column_m"]
    pocket_gauge = model["water_density_kg_m3"] * 9.81 * (hgl - pocket["body_interface_z_m"])
    metadata = {
        "generated_by": "prepare_case.py",
        "openfoam_version": "v2512",
        "application": application,
        "interface_solver": args.interface_solver,
        "mesh_generator": args.mesh_generator,
        "mesh_profile": args.mesh_profile,
        "pocket_profile": args.pocket_profile,
        "pocket_parameters_are_paper_values": False,
        "pocket": pocket,
        "analytic_initial_air_volume_m3": analytic_volume,
        "initial_air_gauge_pressure_Pa": pocket_gauge,
        "main_body_probe_depth_below_crown_m": pocket["thin_layer_m"] + 0.004,
        "thin_layer_refinement_segments": n_thin_refinement,
        "thin_layer_target_cells": (
            pocket["thin_layer_m"] / thin_layer_cell_size
            if args.mesh_generator == "cartesian"
            else 2 ** mesh["thin_layer_level"]
            * pocket["thin_layer_m"]
            / ((2.72 - (-0.05)) / mesh["background_cells"][2])
        ),
        "cartesian_thin_layer_cell_size_m": (
            thin_layer_cell_size if args.mesh_generator == "cartesian" else None
        ),
        "gate_area_m2": gate_area,
        "gate_area_kind": "resolved_geometric",
        "target_effective_discharge_area_m2": model["tailgate_effective_discharge_area_m2"],
        "resolved_gate_discharge_coefficient": model["tailgate_resolved_discharge_coefficient"],
        "gate_area_is_paper_value": False,
        "contact_angle_deg": contact_angle,
        "turbulence_model": turbulence_model,
        "inlet_turbulence_intensity": turbulence_intensity,
        "inlet_turbulence_mixing_length_m": turbulence_length,
        "initial_turbulent_kinetic_energy_m2_s2": k_initial,
        "initial_specific_dissipation_rate_s-1": omega_initial,
        "interface_compression": c_alpha,
        "air_Cp_J_kg_K": model["air_Cp_J_kg_K"],
        "water_bulk_modulus_Pa": model["water_bulk_modulus_Pa"],
        "water_intrinsic_bulk_modulus_Pa": model["water_intrinsic_bulk_modulus_Pa"],
        "water_perfect_fluid_R_J_kg_K": water_r,
        "water_perfect_fluid_rho0_kg_m3": water_rho0,
        "water_reference_density_kg_m3": model["water_density_kg_m3"],
        "water_reference_pressure_Pa": paper["atmospheric_pressure_Pa"],
        "water_reference_temperature_K": paper["temperature_K"],
        "water_eos_wave_speed_m_s": water_wave_speed,
        "water_bulk_modulus_closure": (
            "command-line sensitivity override"
            if water_bulk_overridden
            else (
                "effective rigid-wall fluid modulus from the paper's acrylic-pipe "
                "wave speed; intrinsic water modulus is a sensitivity"
            )
        ),
        "pocket_body_tracer": {
            "field": "pocketBodyTracer",
            "initial_support": "selected upstream main-body gas; thin layer excluded",
            "transport": (
                "conservative air-phase mass fraction using "
                "rhoPhi - interpolate(rho.water)*alphaPhi0.water"
            ),
            "purpose": (
                "main-pocket source identity; alpha.air alone cannot distinguish "
                "the initial thin layer from the body"
            ),
        },
        "initial_field_correction": {
            "pressure": (
                "smooth p_rgh ramp to the static tailwater boundary, then "
                "p = p_rgh + rho_mixture*g.z"
            ),
            "velocity": (
                "axisymmetric constant-Q streamtube through the chamber and "
                "smooth contraction over one downstream-pipe diameter"
            ),
            "gate_contraction_length_m": paper["downstream_diameter_m"],
        },
        "velocity_limit_m_s": velocity_limit if velocity_limit > 0 else None,
        "maxCo": args.max_co,
        "maxAlphaCo": args.max_alpha_co,
        "maxDeltaT": args.max_dt,
        "nProcs": args.np,
        "paper_time_offset_s": model["ramp_start_solver_s"],
        "geometry": geometry_meta,
    }
    write("generated_case.json", json.dumps(metadata, indent=2))
    return metadata


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--mesh-generator",
        choices=("cartesian", "snappy"),
        default="cartesian",
        help="strict-quality cfMesh Cartesian mesh or the retained snappyHexMesh sensitivity",
    )
    parser.add_argument("--mesh-profile", choices=("base", "refined"), default="base")
    parser.add_argument(
        "--pocket-profile",
        choices=("pocket_small", "base", "pocket_large"),
        default="base",
    )
    parser.add_argument(
        "--interface-solver",
        choices=("mules", "iso-advector"),
        default="mules",
        help="VOF transport algorithm; both choices retain compressible energy/EOS physics",
    )
    parser.add_argument("--air-cp", type=float)
    parser.add_argument("--water-bulk-modulus", type=float)
    parser.add_argument(
        "--turbulence-model",
        choices=("laminar", "kOmegaSST"),
        help="override the declared production turbulence closure",
    )
    parser.add_argument("--gate-area", type=float)
    parser.add_argument("--contact-angle", type=float)
    parser.add_argument("--c-alpha", type=float)
    parser.add_argument(
        "--thin-layer-cell-size",
        type=float,
        help=(
            "override only the cfMesh crown-layer cell size; used to isolate "
            "thin-layer resolution from the full refined-mesh profile"
        ),
    )
    parser.add_argument(
        "--velocity-limit",
        type=float,
        default=0.0,
        help=(
            "optional diagnostic maximum |U| in m/s; 0 keeps the production "
            "case free of velocity clipping"
        ),
    )
    parser.add_argument("--max-co", type=float, default=0.35)
    parser.add_argument("--max-alpha-co", type=float, default=0.20)
    parser.add_argument("--max-dt", type=float, default=0.0005)
    parser.add_argument("--np", type=int, default=4)
    args = parser.parse_args()
    metadata = generate(args)
    print(json.dumps(metadata, indent=2))


if __name__ == "__main__":
    main()
