#!/usr/bin/env python3
"""Write a conformal narrow-background block mesh for snappyHexMesh.

A single bounding box would waste millions of cells in empty space between the
6.59 m horizontal pipe and the external atmosphere. This generator instead
uses connected pipe, riser and atmosphere blocks while preserving matching
faces at the tee and physical rim.
"""
from __future__ import annotations

import argparse
import math
from pathlib import Path


PROFILES = {
    "base": {
        "pipe_cross": 0.00625,
        "pipe_axial": 0.015,
        "riser_axial": 0.0125,
        "atmosphere": 0.025,
    },
    "refined": {
        "pipe_cross": 0.005,
        "pipe_axial": 0.010,
        "riser_axial": 0.010,
        "atmosphere": 0.020,
    },
}

X = (0.0, 3.32, 3.44, 3.50, 3.62, 6.59)
Y = (-0.15, -0.03, 0.03, 0.15)
Z = (-0.005, 0.055, 1.85, 3.00)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--profile", choices=sorted(PROFILES), default="base")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("system/blockMeshDict.runtime"),
    )
    return parser.parse_args()


def cells(length: float, target: float) -> int:
    return max(1, math.ceil(length / target))


def main() -> None:
    args = parse_args()
    profile = PROFILES[args.profile]

    vertices: list[tuple[float, float, float]] = []
    index: dict[tuple[int, int, int], int] = {}
    for k, z in enumerate(Z):
        for j, y in enumerate(Y):
            for i, x in enumerate(X):
                index[(i, j, k)] = len(vertices)
                vertices.append((x, y, z))

    blocks: list[tuple[tuple[int, ...], tuple[int, int, int], str]] = []

    def add_block(
        i: int,
        j: int,
        k: int,
        counts: tuple[int, int, int],
        label: str,
    ) -> None:
        v = (
            index[(i, j, k)],
            index[(i + 1, j, k)],
            index[(i + 1, j + 1, k)],
            index[(i, j + 1, k)],
            index[(i, j, k + 1)],
            index[(i + 1, j, k + 1)],
            index[(i + 1, j + 1, k + 1)],
            index[(i, j + 1, k + 1)],
        )
        blocks.append((v, counts, label))

    n_cross = cells(Y[2] - Y[1], profile["pipe_cross"])
    n_pipe_z = cells(Z[1] - Z[0], profile["pipe_cross"])

    # Horizontal-pipe background. The central tee segment uses the transverse
    # count in x so its top face exactly matches the riser bottom face.
    for i in range(len(X) - 1):
        nx = (
            n_cross
            if i == 2
            else cells(X[i + 1] - X[i], profile["pipe_axial"])
        )
        add_block(i, 1, 0, (nx, n_cross, n_pipe_z), "pipe")

    # Narrow vertical-riser background.
    n_riser_z = cells(Z[2] - Z[1], profile["riser_axial"])
    add_block(2, 1, 1, (n_cross, n_cross, n_riser_z), "riser")

    # 3x3 expanded external atmosphere. The central footprint has matching
    # riser counts; outer strips use the coarser atmosphere target.
    n_atmos_z = cells(Z[3] - Z[2], profile["atmosphere"])
    for i in (1, 2, 3):
        for j in (0, 1, 2):
            nx = (
                n_cross
                if i == 2
                else cells(X[i + 1] - X[i], profile["atmosphere"])
            )
            ny = (
                n_cross
                if j == 1
                else cells(Y[j + 1] - Y[j], profile["atmosphere"])
            )
            add_block(i, j, 2, (nx, ny, n_atmos_z), "atmosphere")

    estimated = sum(nx * ny * nz for _, (nx, ny, nz), _ in blocks)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as stream:
        stream.write(
            """/* Generated by make_block_mesh.py; do not commit this runtime file. */
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      blockMeshDict;
}

scale 1;

vertices
(
"""
        )
        for x, y, z in vertices:
            stream.write(f"    ({x:.9g} {y:.9g} {z:.9g})\n")
        stream.write(");\n\nblocks\n(\n")
        for verts, count, label in blocks:
            vtext = " ".join(str(value) for value in verts)
            stream.write(
                f"    hex ({vtext}) ({count[0]} {count[1]} {count[2]}) "
                f"simpleGrading (1 1 1) // {label}\n"
            )
        stream.write(
            """);

edges ();
boundary ();
defaultPatch
{
    name background;
    type patch;
}
mergePatchPairs ();
"""
        )

    print(f"profile={args.profile}")
    print(f"output={args.output}")
    print(f"background_blocks={len(blocks)}")
    print(f"estimated_background_cells={estimated}")
    for key, value in profile.items():
        print(f"{key}_target_m={value}")


if __name__ == "__main__":
    main()
